# -*- coding: utf-8 -*-
"""Auditor Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYKb-C_ImXd72ItvYGTWtF52qCCI0mpa
"""


from db.connection import get_db_connection

conn = get_db_connection()

from langchain.tools import tool

@tool
def get_schema(sample_query: str = "SELECT * FROM users LIMIT 1") -> str:
    """
    Returns column names and types inferred from a sample query.
    Works across all DB-API databases.
    """
    try:
        conn = get_db_connection()
        cur = conn.cursor()

        cur.execute(sample_query)

        if cur.description is None:
            return "No schema available for this query."

        schema = []
        for col in cur.description:
            # col[0] = column name, col[1] = type code
            schema.append(f"{col[0]}")

        cur.close()
        conn.close()

        return "Columns: " + ", ".join(schema)

    except Exception as e:
        return f"Error: {str(e)}"

@tool
def execute_sql(query: str) -> str:
    """
    Executes SQL query on any DB-API compatible database.
    Works with PostgreSQL, SQLite, MySQL, etc.
    """
    try:
        conn = get_db_connection()
        cur = conn.cursor()

        cur.execute(query)

        # SELECT queries return rows
        if cur.description is not None:
            rows = cur.fetchall()
            result = rows
        else:
            conn.commit()
            result = "Query executed successfully"

        cur.close()
        conn.close()

        return str(result)

    except Exception as e:
        return f"Error: {str(e)}"

from langgraph.graph import StateGraph, END, START
from langgraph.graph.message import AnyMessage, add_messages
from langgraph.prebuilt import ToolNode, create_react_agent
from langchain_openai import ChatOpenAI
from typing import Annotated, TypedDict
from langgraph.prebuilt import tools_condition
from langchain_core.messages import AIMessage, SystemMessage, HumanMessage
import os

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

llm = ChatOpenAI(model="gpt-4o-mini")

#analyst agent

analyst_llm = llm.bind_tools([get_schema])

analyst_system_message = [SystemMessage(content="""You are a data analyst. Start by understanding the database schema using tools.
    Then ask at least 10 insightful questions in a single response that will help in creating a comprehensive report.
    """)]

class AnalystState(TypedDict):
  messages: Annotated[list[AnyMessage], add_messages]

def analyst(state: AnalystState) -> AnalystState:
  response = analyst_llm.invoke(analyst_system_message + state["messages"])
  return {"messages": [response]}


analyst_graph = StateGraph(AnalystState)
analyst_graph.add_node("analyst", analyst)
analyst_graph.add_node("tools", ToolNode([get_schema]))

analyst_graph.add_edge(START, "analyst")
analyst_graph.add_conditional_edges("analyst", tools_condition)
analyst_graph.add_edge("tools","analyst")

analyst_app = analyst_graph.compile()

from IPython.display import Image, display

display(Image(analyst_app.get_graph().draw_mermaid_png()))

result = analyst_app.invoke({
    "messages": [HumanMessage(content="Summarize revenue")]
})
print(result["messages"][-1].content)
